# Generated by Django 5.0.6 on 2024-06-26 13:11

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatsConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Statistic Content',
                'verbose_name_plural': 'Statistic Contents',
            },
        ),
    ]
