# Generated by Django 5.0.6 on 2024-06-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statsconcept',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='statsconcept',
            name='content',
            field=models.TextField(),
        ),
    ]
