# Generated by Django 5.0.6 on 2024-06-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0002_statsconcept_slug_alter_statsconcept_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('topic_slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'Concept Topic',
                'verbose_name_plural': 'Concept Topics',
            },
        ),
        migrations.CreateModel(
            name='DataScienceConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_concept_title', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('concept_slug', models.SlugField(blank=True)),
            ],
            options={
                'verbose_name': 'DataScience Concept',
                'verbose_name_plural': 'DataScience Concepts',
            },
        ),
        migrations.CreateModel(
            name='ConceptSubtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtopic_title', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('subtopic_slug', models.SlugField(blank=True)),
                ('content', models.TextField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datascience_topic', to='data_science.concepttopic')),
            ],
        ),
        migrations.AddField(
            model_name='concepttopic',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datascience_topic', to='data_science.datascienceconcept'),
        ),
    ]
