# Generated by Django 5.0.6 on 2024-06-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0003_concepttopic_datascienceconcept_conceptsubtopic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConceptSubtopic',
            new_name='Concept_Subtopic',
        ),
        migrations.RenameModel(
            old_name='ConceptTopic',
            new_name='Concept_Topic',
        ),
        migrations.RenameModel(
            old_name='DataScienceConcept',
            new_name='DataScience_Concept',
        ),
    ]
