# Generated by Django 5.0.6 on 2024-06-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0004_rename_conceptsubtopic_concept_subtopic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataScience_Concept',
            new_name='Concept',
        ),
    ]
