# Generated by Django 5.0.6 on 2024-06-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_science', '0005_rename_datascience_concept_concept'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatsConcept',
        ),
        migrations.AlterField(
            model_name='concept_subtopic',
            name='subtopic_slug',
            field=models.SlugField(unique=True),
        ),
    ]
